name: MS-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
        debug_enabled:
          type: boolean
          description: 'Debug with tmate'
          required: false
          default: false

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: nuget restore ${{github.workspace}}\MagicMetro.sln
    - uses: microsoft/setup-msbuild@v2
    - name: Copy References
      run: |
          mkdir "D:\a\MagicMetro\MagicMetro\MagicMetro\bin\Release"
          cp "C:\Users\runneradmin\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22621.3233\ref\netstandard2.0\Windows.Foundation.FoundationContract.winmd" "D:\a\MagicMetro\MagicMetro\MagicMetro\bin\Release"
          cp "C:\Users\runneradmin\.nuget\packages\microsoft.windows.sdk.contracts\10.0.22621.3233\ref\netstandard2.0\Windows.Foundation.UniversalApiContract.winmd" "D:\a\MagicMetro\MagicMetro\MagicMetro\bin\Release"
    - name: Build
      run: msbuild ${{github.workspace}}\MagicMetro.sln /p:Configuration=Release
    - name: Upload  
      uses: actions/upload-artifact@v4
      with:
        name: MagicMetro
        path: ${{github.workspace}}\MagicMetro\bin\Release\merged\mb_MagicMetro.dll
    - name: Setup tmate session
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      uses: mxschmitt/action-tmate@v3
